services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - json-server

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/app/db.json
